config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'rooms' => 'home/index'
  resources :rooms, only: [:show, :create] do
    member do
      post :join
      post :choice
      get :average
      post :reset
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calculation_result.rb
class CalculationResult < ApplicationRecord
  belongs_to :room
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :player

  def self.list
    %w(1 2 3 5 8 13)
  end
end

app/models/concerns/primary_key_is_uuid.rb
module PrimaryKeyIsUuid
  extend ActiveSupport::Concern

  included do
    before_save :generate_uuid
  end

  def generate_uuid
    self.id = SecureRandom.uuid
  end
end

app/models/player.rb
class Player < ApplicationRecord
  include PrimaryKeyIsUuid

  belongs_to :room
  has_many :choices
end

app/models/room.rb
class Room < ApplicationRecord
  include PrimaryKeyIsUuid

  has_many :players
  has_many :calculation_results

  after_initialize :after_initialize_callback

  def after_initialize_callback
    self.password_for_join = SecureRandom.hex(8)
    self.expired_at = 2.day.from_now
  end

  def join(password_for_join:)
    return false if self.password_for_join != password_for_join
    players.create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_room, only: [:show, :choice, :average, :reset]
  before_action :set_player, only: [:show, :choice, :average]

  def create
    room = Room.new
    room.save!
    redirect_to room
  end

  def show
    @room = Room.find(params[:id])
    @choice = Choice.new
    @last_choice = @player.choices.last&.value
    @average = @room.calculation_results.last&.average
  end

  def choice
    @choice = Choice.new
    @choice.value = params.require(:choice).permit(:choice)[:choice]
    @choice.player = @player
    @choice.save!
    redirect_to @room
  end

  def average
    if @room.calculation_results.present?
      render json: { average: @room.calculation_results.last.average }, status: :ok
      return
    end
    num_player = @room.players.count
    num_votes = @room.players.map(&:choices).flatten.count
    render json: { average: nil }, status: :ok and return if num_player > num_votes
    average = @room.players.map(&:choices).flatten.map(&:value).sum.to_f / num_votes
    @room.calculation_results.create!(average: average)
    render json: { average: @room.players.map(&:choices).flatten.map(&:value).sum.to_f / num_votes }, status: :ok
  end

  def reset
    @room.calculation_results&.map(&:destroy)
    @room.players.map(&:choices).flatten.map(&:destroy)
    redirect_to @room
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def set_player
    if cookies[:player_id].nil?
      @player = Player.new
      @player.room = @room
      @player.save!
      cookies[:player_id] = @player.id
    else
      @player = Player.find_or_create_by!(id: cookies[:player_id], room: @room)
      cookies[:player_id] = @player.id
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<%= form_with url: '/rooms', method: :post do |form| %>
  <%= form.submit('Create Room') %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Purapoka</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/join.html.erb
<h1>Rooms#join</h1>
<p>Find me in app/views/rooms/join.html.erb</p>

app/views/rooms/show.html.erb
<div class="base">
  <details>
    <summary>Room information</summary>
    <p><div id='room-url'><%= room_url @room %></div></p>
  </details>

  <div id='results-panel'>
    <p>Your choice: <span class='number'><%= @last_choice %></span></p>
    <p>Average: <span class='number'><%= @average %></span></p>
  </div>

  <% Choice.list.each do |number| %>
    <%= form_with model: @choice, url: choice_room_path(@room) do |form| %>
      <%= form.hidden_field :room_id, value: @room.id %>
      <%= form.hidden_field :choice, value: number %>
      <%= button_tag number, class: 'button vote' %>
    <% end %>
  <% end %>

  <%= form_with model: @choice, url: reset_room_path(@room) do |form| %>
    <%= form.hidden_field :room_id, value: @room.id %>
    <%= button_tag 'reset', class: 'button reset'  %>
  <% end %>

</div>


<script type="text/javascript">
  document.getElementById('room-url').addEventListener('click', function() {
    var range = document.createRange();
    range.selectNode(this);
    window.getSelection().addRange(range);
  });
</script>
              

<% if @last_choice %>
  <% unless @average %>
    <script type="text/javascript">
      setInterval(function(){
        var xhr = new XMLHttpRequest();
        xhr.open('GET', '<%= average_room_path(@room) %>', true);
        xhr.responseType = 'json';
        xhr.onload = function(e) {
          if (xhr.readyState === 4) {
            if (xhr.status === 200) {
              var response = xhr.response;
              console.log(response);
              if (response.average) {
                // 画面をリロードする
                location.reload();
              }
              //if (response.last_choice) {
              //  console.log(response);
              //}
            }
          }
        };
        xhr.send(null);
      }, 1000);

    </script>
  <% end %>
<% end %>